Added pipline

diff --git a/.github/workflows/cl.yml b/.github/workflows/cl.yml
--- a/.github/workflows/cl.yml
+++ b/.github/workflows/cl.yml
@@ -16,3 +16,12 @@ jobs:
 
       - name: Show files
         run: ls
+
+      - name: Check HTML file exists
+        run: |
+          if [ -f index.html ]; then
+            echo "index.html found! ✅"
+          else
+            echo "index.html NOT found! ❌"
+            exit 1
+          fi
